<?php

/**
 * @file
 * Contains bugherd.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bugherd_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bugherd module.
    case 'help.page.bugherd':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds &lt;a href=&quot;http://www.bugherd.com/&quot;&gt;BugHerd&lt;/a&gt; issue reporting to your site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function bugherd_page_attachments(array &$attachments) {
  /** @var \Drupal\bugherd\Manager\BugherdManager $manager */
  $manager = Drupal::service('bugherd.manager');

  // Checks if bugherd should be loaded.
  if ($manager->pageApplies()) {

    // Pass the settings.
    $attachments['#attached']['drupalSettings']['bugherd'] = $manager->getJsSettings();

    // Load the bugherd js library.
    $attachments['#attached']['library'][] = 'bugherd/bugherd';
  }
}
